import TheHeader from "@/components/TheHeader";
import "./globals.css";
import { Inter } from "next/font/google";
import TheFooter from "@/components/TheFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TheHeader />
        <main className="flex-1 container mx-auto">{children}</main>
        <TheFooter />
      </body>
    </html>
  );
}
